name: Publish to NPM
on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.package_name }}
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: actions/setup-node@v4.0.4
        with:
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}