name: Publish supersprite to NPM
on:
  push:
    branches:
      - main
    paths:
      - supersprite/**
  workflow_dispatch:
jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package_name: supersprite
