name: Publish supercontroller to NPM
on:
  push:
    branches:
      - main
    paths:
      - supercontroller/**
  workflow_dispatch:
jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package_name: supercontroller
    secrets: inherit
