name: Publish supersound to NPM
on:
  push:
    branches:
      - main
    paths:
      - supersound/**
  workflow_dispatch:
jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      package_name: supersound
    secrets: inherit
