name: Run Tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: actions/setup-node@v4.0.4
      - run: |
          cd supersprite
          npm install
          npm run test
        env:
          CI: true
      - run: |
          cd supersound
          npm install
          npm run test
        env:
          CI: true
      - run: |
          cd supercontroller
          npm install
          npm run test
        env:
          CI: true